package nx

type CharacterNX struct {
	// ACC                       any // count=5
	// AbilityTimeLimited        any // count=43
	// AccountSharable           any // count=168
	// AccountShareTag           any // count=101
	// ActionEffect              any // count=2
	// Addition                  any // count=234
	// Additon                   any // count=1
	// Addtion                   any // count=1
	AfterImage string // count=3976
	// Android                   any // count=84
	Attack      int16   // count=3976
	AttackSpeed float64 // count=3980
	// BaseLevel                 any     // count=7
	// BasicEff                  any     // count=1
	BdR int8 // count=122
	// BestFriendPartyBonusExp   any  // count=1
	BitsSlot int16 // count=586
	// Blaze                     any   // count=9
	// BlockGoldHammer           any   // count=3
	// BloodAllianceExpRate      any   // count=1
	// BloodAlliancePartyExpRate any   // count=1
	// BonusAbility              any   // count=24
	BonusExp int32 // count=18
	// Boss                  any  // count=25
	// BossReward            any  // count=827
	// Bowing                any  // count=9
	// CantRepair            any  // count=14
	Cash bool // count=25349
	// CashForceCharmExp     any    // count=134
	// CashTradeBlock        any    // count=27
	// CharismaEXP           any    // count=300
	CharmEXP int64 // count=1134
	// ChatBalloon           any    // count=126
	// ConsumeMP             any    // count=4
	// CraftEXP              any    // count=6
	// CubeExBaseOptionLevel any    // count=89
	CuttableCount int8 // count=2
	// DAexceedLimit        any    // count=4
	// DamR                 any    // count=28
	// DayOfWeekItemStat    any    // count=14
	// Despair              any    // count=9
	// DropBlock            any    // count=22
	Durability int32 // count=143
	// Effect               any    // count=85
	// EffectItemID         any    // count=6
	// ElemDefault          any    // count=16
	// Epic                 any    // count=6
	// EpicItem             any    // count=394
	// EquipDrop            any    // count=2
	EquipTradeBlock int64 // count=2265
	// EquippedEmotion      any    // count=1
	// EquippedSound        any    // count=1
	ExGrade int64 // count=264
	// ExItem               any    // count=1407
	// ExpBuff              any    // count=1
	// ExpRate              any    // count=2
	ExpireOnLogout int64 // count=332
	// ExtendFrame          any    // count=56
	FAttribute int32 // count=52
	// FCategory            any    // count=49
	// FixedGrade           any    // count=138
	// FixedPotential       any    // count=138
	// Fs                   any    // count=9
	// GatherTool           any    // count=22
	// Grade                any    // count=137
	// GroupEffectID        any    // count=6
	// Head                 any    // count=90
	// Hide                 any    // count=6
	// HitDamRatePlus       any    // count=1
	// Hot                  any    // count=9
	// HpRecovery           any    // count=8
	// Hum                  any    // count=9
	// IUCMax               any    // count=1
	// IcnSTR               any    // count=3
	// Icon                 any    // count=17797
	// Icon1                any    // count=1
	// Icon2                any    // count=1
	// Icon3                any    // count=1
	// Icon4                any    // count=1
	// Icon5                any    // count=1
	// Icon6                any    // count=1
	// Icon7                any    // count=1
	// IconD                any    // count=84
	// IconRaw              any    // count=17797
	// IconRaw2             any    // count=1
	// IconRaw3             any    // count=1
	// IconRaw4             any    // count=1
	// IconRaw5             any    // count=1
	// IconRaw6             any    // count=1
	// IconRaw7             any    // count=1
	// IconRawD             any    // count=84
	// ImdR                 any    // count=144
	// InPAD                any    // count=1
	IncACC int16 // count=1721
	// IncALL               any    // count=1
	// IncAttackCount       any    // count=1
	// IncCr                any    // count=1
	IncCraft int16 // count=53
	// IncCriticalMAXDamage any    // count=1
	// IncDAMr              any    // count=1
	IncDEX int16 // count=4858
	IncEVA int16 // count=1215
	// IncFatigue           any    // count=8
	// IncHP                any    // count=1
	IncINT  int16 // count=3732
	IncJump int16 // count=541
	IncLUK  int16 // count=4166
	// IncLUk               any    // count=1
	// IncLuk               any    // count=1
	IncMAD int16 // count=2833
	IncMDD int16 // count=2855
	// IncMDDr              any    // count=1
	IncMHP int16 // count=2178
	// IncMHPr              any    // count=27
	IncMMP int16 // count=1936
	// IncMMPr              any    // count=21
	// IncMSpeed            any    // count=5
	IncPAD int16 // count=6427
	IncPDD int16 // count=4918
	// IncPDDr              any    // count=1
	IncPVPDamage int16 // count=34
	// IncRMAF              any    // count=8
	// IncRMAI              any    // count=8
	// IncRMAL              any    // count=8
	// IncRMAS              any    // count=8
	IncSTR   int16 // count=4764
	IncSpeed int16 // count=948
	// IncSwim              any    // count=8
	// Info                 any    // count=1
	// InsightEXP           any    // count=7
	// IntLUK               any    // count=12
	// InvisibleFace        any    // count=38
	// IsAbleToTradeOnce    any    // count=11
	// Islot string // count=27472
	// JewelCraft           any    // count=2
	// JokerToSetItem       any    // count=34
	// KaiserOffsetX        any    // count=6
	// KaiserOffsetY        any    // count=6
	// KeywordEffect        any    // count=3
	// Knockback            any    // count=363
	Level      int8  // count=381
	LimitBreak int64 // count=355
	// LinkedPairItem       any   // count=3
	// LongRange            any   // count=4
	// LookChangeType       any   // count=33
	// Love                 any   // count=9
	// MDD                  any   // count=6
	// MHP                  any   // count=6
	// MMP                  any   // count=6
	// MasterSpecial        any   // count=8
	// MaxHP                any   // count=3
	// MedalTag             any   // count=727
	// Mob                  any   // count=2
	// MobID                any   // count=161
	// MonsterCardID        any   // count=161
	// MpRecovery           any   // count=8
	// NActivatedSocket     any   // count=46
	// NameTag              any   // count=105
	// Night                any   // count=4
	// NoDrop               any   // count=4
	// NoExpend             any   // count=15
	// NoExtend             any   // count=4
	// NoMoveToLocker       any   // count=193
	// NoPotential          any   // count=55
	// NoPotentialFieldtype any   // count=5
	// NotExtend            any   // count=343
	NotSale     int64 // count=3700
	Only        bool  // count=2033
	OnlyAndroid bool  // count=17
	OnlyCash    bool  // count=20
	OnlyEquip   bool  // count=500
	OnlyHeart   bool  // count=5
	OnlyUpgrade bool  // count=28
	// Option            any   // count=138
	// Origin            any   // count=5
	// PDD               any   // count=6
	// Pachinko          any   // count=42
	// Pad               any   // count=10
	// PartsCount        any   // count=1
	// PartsQuestID      any   // count=1
	// PassengerNum      any   // count=3
	// PickUpBlock       any   // count=4
	// PickupItem        any   // count=4
	// PickupMeso        any   // count=4
	// PickupOthers      any   // count=4
	// PmdR              any   // count=1
	Price int32 // count=10940
	// Quest             any   // count=6
	// RandVariation     any   // count=19
	// Range             any   // count=161
	// Recovery          any   // count=7
	ReduceReq int8 // count=32
	// RemoveBody        any   // count=4
	// Replace           any   // count=21
	ReqDEX     int16 // count=15399
	ReqINT     int16 // count=15381
	ReqJob     int16 // count=17032
	ReqJob2    int16 // count=179
	ReqLUK     int16 // count=15390
	ReqLevel   int16 // count=17339
	ReqPOP     int16 // count=79
	ReqSTR     int16 // count=15412
	ReqSpecJob int16 // count=331
	// RingOptionSkill   any   // count=36
	// RingOptionSkillLv any   // count=36
	// RoyalSpecial      any   // count=19
	// Sample            any   // count=297
	// ScanTradeBlock    any   // count=7
	// Scope             any   // count=32
	// Sealed            any   // count=40
	// SenseEXP          any   // count=6
	SetItemID int32 // count=3402
	// Sfx          int32 // count=3975
	// SharableOnce any   // count=93
	// Shine        any   // count=9
	// Skill        any   // count=161
	// SkillID      any   // count=68
	// SlotMax      any   // count=598
	// SpecialGrade any   // count=137
	// SpecialID    any   // count=25
	// Speed        any   // count=65
	Stand int64 // count=3975
	// StarPlanet   any   // count=2
	// SuperiorEqp  any   // count=55
	// SweepForDrop any   // count=4
	// TamingMob    any   // count=405
	// Text         any   // count=2
	// TextAreaX    any   // count=2
	// TextAreaY    any   // count=2
	// TextColor    any   // count=2
	// TextFontSize any   // count=2
	// TextOffsetX  any   // count=2
	// TextOffsetY  any   // count=2
	TimeLimited int64 // count=1523
	// TimeLimited               any // count=16
	// ToolTipAdjustLeft any  // count=1
	// ToolTipAdjustTop  any  // count=1
	// TradBlock         any  // count=2
	TradeAvailable bool // count=1682
	TradeBlock     bool // count=6016
	// TradeBlock             any // count=9
	Tuc int8 // count=11279
	// Unchangeable           any    // count=49
	// Undecomposable         any    // count=2
	// VariableStat           any    // count=30
	// VehicleDefaultFrame    any    // count=56
	// VehicleDoubleJumpLevel any    // count=160
	// VehicleGlideLevel      any    // count=24
	// VehicleNaviFlyingLevel any    // count=98
	// VehicleNewFlyingLevel  any    // count=41
	// VehicleSkillIsTown     any    // count=36
	// Vslot   string // count=27450
	Walk int64 // count=3975
	// Weekly  any   // count=2
	WillEXP int64 // count=305
}
