package nx

type ItemNX struct {
	// AccountSharable         any   // count=628
	// AccountShareTag         any   // count=1
	// AccountShareable        any   // count=1
	// Add                     any   // count=19
	// AddDay                  any   // count=2
	// AddTime                 any   // count=39
	// AllowOverlappedSet      any   // count=3
	// Animation_create        any   // count=2
	// Animation_dropped       any   // count=2
	// AutoBuff                any   // count=196
	// AutoPrice               any   // count=837
	// AutoReact               any   // count=8
	// AutoSpeaking            any   // count=1
	BagType int8 // count=192
	// BarrierEffectLimit      any   // count=1
	// BarrierEffectProp_13    any   // count=1
	// BarrierEffectProp_14    any   // count=1
	// BarrierEffectProp_15    any   // count=1
	// BgmInfo                 any   // count=7
	// BgmPath                 any   // count=13
	BigSize int64 // count=1137
	// BodyRelMove             any   // count=463
	// BonusEXPRate            any   // count=1
	// BonusStageItem          any   // count=15
	// Bottom                  any   // count=42
	// BridleMsgType           any   // count=12
	// BridleProp              any   // count=3
	// BridlePropChg           any   // count=3
	// BridlePropZeroMsg       any   // count=2
	// BuffItemID              any   // count=13
	// Buffchair               any   // count=1
	// Burning                 any   // count=1
	// Camouflage              any   // count=2
	// CanAccountSharable      any   // count=1
	// CanUseJob               any   // count=1
	// CantAccountSharable     any   // count=5
	Cash bool // count=3176
	// CashExpTicketOn         any   // count=22
	// CashTradeBlock          any   // count=10
	// CharismaEXP             any   // count=4
	// CharmEXP                any   // count=6
	ChatBalloon int64 // count=302
	// Commerce                any   // count=12
	// ConsumableFrom          any   // count=71
	// ConsumableFrom_CN       any   // count=7
	ConsumeHP int64 // count=44
	// ConsumeItem             any   // count=72
	// ConsumeMP               any   // count=25
	// Consumeitem             any   // count=1
	// Continuity              any   // count=1
	// CraftEXP                any   // count=1
	// Create                  any   // count=41
	// CreatePeriod            any   // count=4
	// CreateType              any   // count=7
	Cursed int64 // count=838
	// Cursor                  any   // count=11
	// Cuttable                any   // count=9
	// Dama                    any   // count=5
	// DelayMsg                any   // count=5
	// Direction               any   // count=80
	// DistanceX               any   // count=27
	// DistanceY               any   // count=27
	// DressUpgrade            any   // count=3
	// DropBlock               any   // count=31
	// DropExpireTime          any   // count=2
	// DropSweep               any   // count=2
	// Effect                  any   // count=15
	// EffectByItemID          any   // count=109
	// Emotion                 any   // count=54
	// EndLotteryDate          any   // count=37
	// EndUseDate              any   // count=178
	// Evol                    any   // count=14
	// Evol1                   any   // count=14
	// Evol2                   any   // count=11
	// Evol3                   any   // count=11
	// Evol4                   any   // count=7
	// Evol5                   any   // count=1
	// EvolNo                  any   // count=14
	// EvolProb1               any   // count=14
	// EvolProb2               any   // count=11
	// EvolProb3               any   // count=11
	// EvolProb4               any   // count=7
	// EvolProb5               any   // count=1
	// EvolReqItemID           any   // count=14
	// EvolReqPetLvl           any   // count=11
	// EvolutionID             any   // count=9
	// ExGrade                 any   // count=35
	// ExGradeWeight           any   // count=35
	// ExNew                   any   // count=9
	// Exp                     any   // count=166
	// ExpRate                 any   // count=22
	// ExpandLimit             any   // count=1
	ExpireOnLogout int64 // count=259
	// Face                    any   // count=9
	// FamiliarID              any   // count=1021
	// FixFrameIdx             any   // count=19
	// FlatRate                any   // count=26
	// Flip                    any   // count=3
	FloatType int64 // count=207
	// Follow                  any   // count=6
	// Font                    any   // count=12
	// ForceUpgrade            any   // count=38
	// ForcingItem             any   // count=5
	// Gender                  any   // count=2
	// GiantPet                any   // count=20
	// Grade                   any   // count=1108
	// GroupTWInfo             any   // count=2
	// Guild                   any   // count=1
	Hungry int64 // count=323
	// Hybrid                  any   // count=47
	// Icon                    any   // count=27034
	// Icon1                   any   // count=12
	// IconD                   any   // count=374
	// IconEnter               any   // count=3
	// IconLarge               any   // count=89
	// IconLeave               any   // count=3
	// IconRaw                 any   // count=27004
	// IconRawD                any   // count=326
	// IconReward              any   // count=235
	// IconShop                any   // count=116
	// IgnorePickup            any   // count=1
	// IgnoreTendencyStatLimit any   // count=50
	IncACC int16 // count=344
	// IncALB   any   // count=22
	// IncCraft any   // count=2
	IncDEX  int16 // count=692
	IncEVA  int16 // count=192
	IncINT  int16 // count=596
	IncJump int16 // count=38
	IncLEV  int8  // count=2
	IncLUK  int16 // count=594
	IncMAD  int16 // count=380
	IncMDD  int16 // count=293
	IncMHP  int16 // count=312
	IncMMP  int16 // count=207
	// IncMax                      any   // count=1
	// IncMaxHP                    any   // count=3
	// IncMaxMP                    any   // count=3
	IncPAD int16 // count=806
	IncPDD int16 // count=345
	// IncPERIOD                   any     // count=1
	// IncPVPDamage                any     // count=1
	// IncRandVol                  any     // count=21
	// IncReqLevel                 any     // count=3
	IncSTR         int16 // count=683
	IncSpeed       int16 // count=53
	IncattackSpeed int16 // count=14
	// InteractByUserAction        any     // count=1
	// InvisibleWeapon             any     // count=100
	// IsBgmOrEffect               any     // count=13
	// IsSoulBinder                any     // count=9
	// ItemPoint                   any     // count=14
	// Karma                       any     // count=4
	// Left                        any     // count=42
	// Level                       any     // count=8
	// LevelDX                     any     // count=6
	// LevelGroup                  any     // count=4
	// LevelVariation              any     // count=3
	Life int64 // count=330
	// Limit                       any     // count=5
	// LimitMin                    any     // count=34
	// LimitedLife                 any     // count=3
	// LimitedLv                   any     // count=4
	LongRange int64 // count=44
	// Lt                          any     // count=7
	// Lv                          any     // count=932
	// LvChairInfo                 any     // count=1
	// LvMax                       any     // count=9
	// LvMin                       any     // count=9
	// LvOptimum                   any     // count=177
	// LvRange                     any     // count=170
	// LvUpWarning                 any     // count=11
	// Map                         any     // count=4
	// MasterLevel                 any     // count=1070
	// Max                         any     // count=113
	// MaxDX                       any     // count=6
	// MaxDays                     any     // count=43
	// MaxDiff                     any     // count=27
	// MaxExp                      any     // count=22
	// MaxLength                   any     // count=2
	// MaxLevel                    any     // count=13
	// MaxSuperiorEqp              any     // count=1
	// McType                      any     // count=17
	Meso int64 // count=6
	// MesoChair                   any     // count=1
	// Message                     any     // count=137
	// MinusLevel                  any     // count=26
	// Mob                         any     // count=955
	// MobHP                       any     // count=37
	// MobId                       any     // count=6
	// MobPotion                   any     // count=2
	// MonsterBook                 any     // count=913
	// MorphItem                   any     // count=16
	// MultiPet                    any     // count=222
	// Name                        any     // count=93
	// NameInfo                    any     // count=3
	NameTag int64 // count=303
	// NickSkill                   any     // count=189
	// NickSkillTimeLimited        any     // count=36
	// NickTag                     any     // count=308
	// NoCancel                    any     // count=3
	// NoCancelMouse               any     // count=157
	// NoCursed                    any     // count=34
	// NoDrop                      any     // count=317
	// NoExpend                    any     // count=10
	// NoFlip                      string  // count=1
	// NoHungry                    any     // count=2
	// NoMoveIcon                  any     // count=3
	// NoMoveToLocker              any     // count=204
	// NoNegative                  any     // count=22
	// NoRecovery                  any     // count=2
	// NoRevive                    any     // count=26
	// NoRotateIcon                any     // count=5
	// NoRucDecrease               any     // count=1
	// NoSale                      any     // count=5
	// NoScroll                    any     // count=7
	// NoShadow                    any     // count=11
	// NoSound                     any     // count=14
	// NoSuperior                  any     // count=2
	// NomobMsg                    any     // count=7
	// NormalPet                   any     // count=1
	NotConsume     bool // count=1874
	NotExtend      bool // count=341
	NotPickUpByPet bool // count=10
	NotSale        bool // count=6188
	// Npc                         any     // count=15
	// Num                         any     // count=12
	Only int64 // count=1812
	// Origin                      any     // count=3
	// Pachinko                    any     // count=3
	// PartyExpOn                  any     // count=22
	Path string // count=421
	// Path4Top                    any     // count=1
	// PerfectReset                any     // count=3
	// Permanent                   any     // count=15
	// PickUpBlock                 any     // count=48
	PickupAll  int64 // count=52
	PickupItem int64 // count=306
	// Picture                     any     // count=34
	// Point                       any     // count=6
	// PointCost                   any     // count=26
	// Pos                         any     // count=12
	// Pquest                      any     // count=119
	// Preventslip                 any     // count=1
	Price int32 // count=20114
	// PriceCoin                   any     // count=1021
	// ProtectTime                 any     // count=4
	// PurchaseShop                any     // count=7
	// PvpChannelLimited           any     // count=29
	Quest   int64 // count=3213
	QuestId int32 // count=99
	// RandEffect                  any     // count=9
	// RandOption                  any     // count=3
	// RandStat                    any     // count=3
	// Random                      any     // count=16
	// RandomChair                 any     // count=8
	// Randstat                    any     // count=59
	Rate int64 // count=45
	// Ratef                       any     // count=3
	// Rb                          any     // count=7
	// Recall                      any     // count=1
	// Recover                     any     // count=33
	RecoveryHP int16 // count=1133
	// RecoveryHPr                 any     // count=4
	RecoveryMP int16 // count=1016
	// RecoveryMPr                 any     // count=4
	// RecoveryRate                any     // count=7
	// RemoveBody                  any     // count=6
	// RemoveCharacterInfo         any     // count=3
	// RemoveEffect                any     // count=114
	// Repeat                      any     // count=12
	// Replace                     any     // count=99
	ReqCUC           int8 // count=4
	ReqEquipLevelMax int8 // count=52
	ReqEquipLevelMin int8 // count=15
	ReqGuildLevel    int8 // count=1
	ReqLevel         int8 // count=868
	// ReqMap                      any     // count=2
	// ReqQuestOnProgress          any     // count=138
	// ReqRUC                      any     // count=1
	// ReqSkillLevel               any     // count=1022
	// Reset                       any     // count=16
	// ResetRUC                    any     // count=1
	// RewardItemID                any     // count=24
	// Right                       any     // count=42
	// RotateSpeed                 any     // count=2
	// RunOnPickup                 any     // count=1
	// RunScript                   any     // count=18
	// SafetyShield                any     // count=40
	// Sample                      any     // count=328
	// ScanTradeBlock              any     // count=6
	// SelectedSlot                any     // count=26
	// SenseEXP                    any     // count=15
	// SetID                       any     // count=1
	// SetItemCategory             any     // count=12
	// SetItemID                   any     // count=176
	// SetPet                      any     // count=1
	// SharableOnce                any     // count=46
	// SharedStatCostGrade         any     // count=7
	// Shop                        any     // count=2
	// ShowMessage                 any     // count=1
	// SitAction                   any     // count=162
	// SitEmotion                  any     // count=65
	// SitLeft                     any     // count=78
	// Skill                       any     // count=1071
	// SkillCast                   any     // count=3
	// SkillEffectID               any     // count=3
	// SlotIndex                   any     // count=2
	// SlotMat                     any     // count=2
	SlotMax int16 // count=14453
	// SmartPet                    any     // count=1
	// SoldInform                  any     // count=20
	// SoulItemType                any     // count=5
	// Spec                        any     // count=3
	// SpecialItem                 any     // count=5
	// SpecificDX                  any     // count=1
	// Speed                       any     // count=49
	// StarPlanet                  any     // count=4
	// StarPlanetPet               any     // count=2
	StateChangeItem int64 // count=70
	// StateType                   any     // count=3
	// Succece                     any     // count=2
	Success         int64   // count=4343
	SuccessRates    float64 // count=34
	SummonSoulMobID int32   // count=544
	SweepForDrop    int64   // count=47
	TamingMob       int32   // count=290
	// TargetFieldID               any     // count=5
	// TextInfo                    any     // count=18
	// TicketItemID                any     // count=2
	// TicketItemUse               any     // count=5
	// TicketLimitedEntranceHeader any     // count=2
	// TicketLimitedEntranceNumber any     // count=2
	// Time                        any     // count=59
	TimeLimited int64 // count=3075
	// Top            any     // count=42
	// TopOffset      any     // count=26
	// TowerBottom    any     // count=26
	// TowerTop       any     // count=26
	// TradBlock      any     // count=1
	// TradeAvailable bool    // count=469
	TradeBlock bool // count=10684
	// TradeReward   any     // count=2
	// TragetBlock   any     // count=2
	Tuc  int8  // count=39
	Type int64 // count=706
	// UI            any     // count=10
	// UILink        any     // count=6
	// UiData        any     // count=93
	UnitPrice float64 // count=42
	// UseDelay      any     // count=7
	// UseTradeBlock any     // count=36
	// Waittime      any     // count=1
	// Warmsupport   any     // count=1
	// WillEXP       any     // count=1
	// Consume spec
	Acc int16 // count=162
	// AccRate     any   // count=7
	// AsrR        any   // count=3
	// AttackIndex any   // count=1
	// AttackMobID any   // count=1
	// Awake       any   // count=1
	// BFSkill     any   // count=7
	// Barrier     any   // count=1
	// BdR         any   // count=3
	// Berserk     any   // count=6
	// Booster     any   // count=8
	// Boss        any   // count=1
	// Bs          any   // count=3
	// BsUp        any   // count=1
	// CaptureBuff any   // count=2
	// CharismaEXP          any // count=10
	// CharmEXP             any // count=10
	// Con             any // count=597
	// ConsumeDummy    any // count=4
	// ConsumeOnPickup any // count=1079
	// Cosmetic        any // count=101
	// Cp              any // count=3
	// CraftEXP             any // count=10
	// CriticalProb     any // count=9
	// Curse            any // count=11
	// Darkness         any // count=11
	// Deathmark        any // count=1
	// DebuffTolerance  any // count=1
	// DefenseAtt       any // count=69
	// DefenseState     any // count=28
	// Dex              any // count=70
	// DexR             any // count=1
	// DojangLuckyBonus any // count=1
	// Dojangshield     any // count=2
	// DropRIncrease    any // count=5
	// DropRate         any // count=4
	// EffectedOnAlly   any // count=8
	// Eva              any // count=155
	// EvaRate          any // count=7
	// EvadeProb        any // count=4
	// EventPoint       any // count=1
	// EventRate        any // count=1
	// Exp                  any // count=13
	// ExpBuff          any // count=113
	// Expinc           any // count=4
	// FieldExpType     any // count=3
	// GatherDropR      any // count=2
	// GatherDropRCount any // count=2
	// Ghost            any // count=5
	// Grade                any // count=5
	Hp int16 // count=454
	// HpR               any   // count=88
	// Hue               any   // count=1
	// IgnoreContinent   any   // count=24
	// IgnoreMobpdpR     any   // count=3
	// Imhp              any   // count=7
	// Immortal          any   // count=1
	// Immp              any   // count=6
	// IncEffectHPPotion any   // count=2
	// IncEffectMPPotion any   // count=2
	// IncFatigue        any   // count=1
	// IncFixedDamageR   any   // count=16
	// IncPVPDamage         any // count=5
	// IncRepleteness      any // count=9
	// IncTameness         any // count=9
	// IndieAcc            any // count=9
	// IndieAllStat        any // count=18
	// IndieBDR            any // count=5
	// IndieBooster        any // count=4
	// IndieDEX            any // count=6
	// IndieDamR           any // count=2
	// IndieEva            any // count=7
	// IndieExp            any // count=7
	// IndieForceJump      any // count=1
	// IndieForceSpeed     any // count=1
	// IndieINT            any // count=6
	// IndieIgnoreMobpdpR  any // count=3
	// IndieJump           any // count=48
	// IndieLUK            any // count=6
	// IndieMad            any // count=218
	// IndieMdd            any // count=64
	// IndieMhp            any // count=61
	// IndieMhpR           any // count=11
	// IndieMmp            any // count=36
	// IndieMmpR           any // count=1
	// IndiePad            any // count=219
	// IndiePdd            any // count=64
	// IndieQrPointTerm    any // count=2
	// IndieSTR            any // count=6
	// IndieScriptBuff     any // count=8
	// IndieSpeed          any // count=81
	// IndieStance         any // count=1
	// IndieStatR          any // count=3
	// IndieWaterSmashBuff any // count=5
	// Inflation           any // count=21
	// InsightEXP          any // count=10
	// Int                 any // count=65
	// IntR                any // count=1
	// ItemCode            any // count=9
	// ItemInvincible      any // count=7
	// ItemRange           any // count=8
	// Itemupbyitem        any // count=147
	// Jump                any // count=171
	// LifeId              any // count=23
	// Luk                 any // count=70
	// LukR                any // count=1
	// Mad                 any // count=246
	// MadRate             any // count=7
	// Mdd                 any // count=76
	// MddRate             any // count=7
	// Mesoupbyitem        any // count=93
	// MhpR                any // count=7
	// MhpRRate            any // count=7
	// Mhp_temp            any // count=3
	// MmpR                any // count=7
	// MmpRRate            any // count=7
	// Mmp_temp            any // count=3
	// Mob                  any // count=1
	// MobHp          any   // count=1
	// MobID          any   // count=2
	// Morph          any   // count=216
	// MorphRandom    any   // count=4
	// MoveTo         any   // count=61
	Mp int16 // count=201
	// MpR            any   // count=86
	// NoTimeLimit    any   // count=2
	// NotPickupByPet any   // count=1
	// Npc                  any // count=3683
	// NuffSkill            any // count=3
	// OnlyPickup           any // count=93
	// OtherParty           any // count=1
	// Pad                  any // count=259
	// PadRate              any // count=7
	// Painmark             any // count=3
	// Party                any // count=9
	// Pdd                  any // count=100
	// PddRate              any // count=7
	// PlusExpRate          any // count=10
	// PlusFameExpRate      any // count=1
	// PlusPurifyStone      any // count=1
	// Poison               any // count=11
	// Prob                 any // count=264
	// RandomMoveInFieldSet any // count=1
	// RandomPickup         any // count=2
	// RandomPickupConsume  any // count=2
	// RealConsumeItems     any // count=4
	// RechargeDrop         any // count=1
	// RechargeDropTime     any // count=1
	// Recipe               any // count=1102
	// RecipeUseCount       any // count=793
	// RecipeValidDay       any // count=97
	// RepeatEffect         any // count=15
	// ReqSkill             any // count=421
	// ReqSkillLevel        any // count=1102
	// ReqSkillProficiency any // count=568
	// RespectFS           any // count=3
	// RespectMimmune      any // count=4
	// RespectPimmune      any // count=3
	// ReturnMapQR         any // count=12
	// RunOnPickup         any // count=306
	// ScreenMsg any    // count=3
	Script string // count=3693
	// Seal   any    // count=11
	// SenseEXP    any // count=10
	// SkillID     any // count=21
	// SlotCount   any // count=4
	// SlotPerLine any // count=4
	// Speed       any // count=245
	// SpeedRate any // count=7
	// Str       any // count=69
	// StrR      any // count=1
	// Thaw      any // count=10
	// Time      any // count=2171
	// Type     any // count=4
	// Weakness any // count=11
	// WillEXP  any // count=10
}
