package opcode

const (
	SendSecurityPacket                     CClientSocket          = 102
	SendPermissionRequest                  CClientSocket          = 103
	CheckLoginAuthInfo                     CLogin                 = 105
	SendSelectWorldButton                  CLogin                 = 106
	SendSelectWorldRequest                 CLogin                 = 107
	SendCheckSPWRequest                    CLogin                 = 108
	WorldScreenLoaded                      CLogin                 = 110
	SendCheckSPWExistPacket                CLogin                 = 111
	MigrateIn                              CClientSocket          = 113
	SendSelectCharacterRequest             CLogin                 = 114 // Click start game button
	SendWorldInformation                   CLogin                 = 116
	SendCheckDuplicateIDPacket             CLogin                 = 117
	GotoWorldSelect                        CLogin                 = 118
	SendNewCharPacket                      CLogin                 = 126
	SendDeleteCharPacket                   CLogin                 = 128
	SendReservedDeleteCharacterConfirmStep CLogin                 = 129
	SendReservedDeleteCharacterCancelStep  CLogin                 = 130
	SendExceptionLog                       CClientSocket          = 132
	SendSecurityHandle                     CClientSocket          = 145
	_                                      CClientSocket          = 150
	OnAliveReq_Callback                    CClientSocket          = 152
	_                                      CClientSocket          = 153
	OnCheckAliveAck_Callback               CClientSocket          = 154 // not sure
	SendBackupPacket                       CWvsApp                = 155 // Client dump log
	CRCErrorLog                            CClientSocket          = 156
	SendGenderSetRequest                   CLogin                 = 162
	BackToLoginScreen                      CLogin                 = 163
	ApplyHotfix                            CClientSocket          = 170
	SendWvsSetupStep                       CWvsApp                = 172
	CrashReporter_PreCallback              CWvsApp                = 173
	SendNewCharPacket_ClientToGame         CLogin                 = 179 // After created new character and auto enter game
	SendChangeCharOrderRequest             CLogin                 = 180
	SendCurrentWorldID                     CLogin                 = 196
	BeginUser                              CClientSocket          = 203
	LoginScreenLoaded                      CLogin                 = 205
	SendMigrateToShopRequest               CWvsContext            = 209
	TryDoingMeleeAttack                    CUserLocal             = 221
	TryDoingShootAttack                    CUserLocal             = 222
	TryDoingMagicAttack                    CUserLocal             = 223
	SendDefaultWingItemChange              CWvsContext            = 245
	StartNavigation                        CWvsContext            = 329
	SendSkillCancelRequest                 CUserLocal             = 350
	StartQuest                             CQuest                 = 369
	FlushToSvr                             CMacroSysMan           = 377
	OnSetPassenserRequest_Callback         CWvsContext            = 391
	RegResult                              CUIMesoMarketDlg       = 421 // UnRegResult RemoveResult
	OnCheckWeddingExResult_Callback        CWvsContext            = 443
	SendGuildHandle                        CField                 = 451
	OnMarriageRequest_Callback             CWvsContext            = 480
	OpenCard                               CBoardGameCell         = 521
	SendCharacterBurning                   CLogin                 = 522
	SetDressChangedState                   CWvsContext            = 534
	ProcessReturnToCharacterSelect         CWvsContext            = 550
	TryMentoringTeleport                   CWvsContext            = 560
	OnUserDamageOnFallingCheck_Callback    CWvsContext            = 577
	OnMobDropMesoPickup_Callback           CWvsContext            = 579
	OnBreakTimeFieldEnter_Callback         CWvsContext            = 580
	OnRuneActSuccess_Callback              CWvsContext            = 581
	SaveQuickslotKeyMap_Callback           CQuickslotKeyMappedMan = 708
	OnMemoInGameNotify_Receive             CWvsContext            = 717
	OnBossArenaMatchFail_Callback          CWvsContext            = 740
	SendPingCheckRequest_ClientToGame      CWvsApp                = 866
	SendPlantPotClick                      CWvsApp                = 868
	ClearResWarriorCurrentAttack           CUserLocal             = 900
	CheckNewBattleRecordTimeout            CBattleRecordMan       = 1573
	EndUser                                CClientSocket          = 2048
)
