package opcode

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strconv"
)

type (
	CUserLocal       uint16
	CQuest           uint16
	CMacroSysMan     uint16
	CUIMesoMarketDlg uint16
	CBoardGameCell   uint16
	CBattleRecordMan uint16
)

type (
	CLogin                   uint16
	CClientSocket            uint16
	CWvsContext              uint16
	CUIFieldItem             uint16
	CUIFieldItemInventory    uint16
	CUIGuildContentRank      uint16
	CUIButterFlyCustomize    uint16
	CInvasionSupportMan      uint16
	CUIEquipmentEnchant      uint16
	CStage                   uint16
	CField                   uint16
	CQuickslotKeyMappedMan   uint16
	CInGameDirectionNodeInfo uint16
	CWvsApp                  uint16
	CUICoordinationContest   uint16
	CUIStatusBar             uint16
	FieldDelaySkill          uint16
	CFieldRankSystem         uint16
	CRuneStoneMgrForClient   uint16
)

var (
	NotLogInSet map[uint16]struct{} = map[uint16]struct{}{
		uint16(SendSecurityHandle): {},
		uint16(SendWvsSetupStep):   {},
		// uint16(OnAliveReq_Callback): {},
	}
	NotLogOutSet map[uint16]struct{} = map[uint16]struct{}{
		// uint16(OnAliveReq): {},
	}
)

// Convert opcode to map[uint16]string for Debug
func GenOpcodeMap(originPath, targetPath, mapName string) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, originPath, nil, parser.AllErrors)
	if err != nil {
		panic(err)
	}
	out, err := os.Create(targetPath)
	if err != nil {
		panic(err)
	}
	defer out.Close()
	fmt.Fprintln(out, "// Code generated by opcode_test, DO NOT EDIT.")
	fmt.Fprintln(out, "package opcode")
	fmt.Fprintf(out, "\nvar %s map[uint16]string = map[uint16]string{", mapName)
	fmt.Fprintln(out, "")
	ast.Inspect(f, func(n ast.Node) bool {
		switch v := n.(type) {
		case *ast.ValueSpec:
			for _, name := range v.Names {
				if value, err := strconv.Atoi(v.Values[0].(*ast.BasicLit).Value); err == nil {
					fmt.Fprintf(out, "\t%d: \"%s\",\n", value, name.Name)
				}
			}
		}
		return true
	})
	fmt.Fprintln(out, "}")
}
