package opcode

const (
	OnCheckPasswordResult                 CLogin                   = 0 // Login failed or banned
	OnWorldInformation                    CLogin                   = 1
	OnLatestConnectedWorld                CLogin                   = 2 // Back to select world screen
	OnSetClientKey                        CLogin                   = 3 // Unuse
	OnSetPhysicalWorldID                  CLogin                   = 4
	OnSelectWorldButton                   CLogin                   = 5 // V199 new and show channel list
	OnSelectWorldResult                   CLogin                   = 6 // LoginServer World
	OnSelectCharacterResult               CLogin                   = 7 // LoginServer -> ChannelServer
	OnAccountInfoResult                   CLogin                   = 8
	OnCreateMapleAccountResult            CLogin                   = 9
	OnCheckDuplicatedIDResult             CLogin                   = 10 // Check duplicated name when create new character
	OnCreateNewCharacterResult            CLogin                   = 11
	OnDeleteCharacterResult               CLogin                   = 12
	OnReservedDeleteCharacterResult       CLogin                   = 13
	OnReservedDeleteCharacterCancelResult CLogin                   = 14
	OnSetCharacterID                      CLogin                   = 15
	OnMigrateCommand                      CClientSocket            = 16
	OnAliveReq                            CClientSocket            = 17
	OnChannelAliveReq                     CClientSocket            = 18 // not sure
	OnChatServerResult                    CClientSocket            = 19 // [bool,CharacterID]
	OnPingCheckResult                     CClientSocket            = 20
	OnAuthenCodeChanged                   CClientSocket            = 21
	OnAuthenMessage                       CClientSocket            = 22
	OnSecurityPacket                      CClientSocket            = 23 // [1,0] CSecurityClient::OnPacket
	OnPrivateServerAuth                   CClientSocket            = 24 // Deprecated
	_                                     CLogin                   = 28
	_                                     CLogin                   = 29 // return
	_                                     CLogin                   = 30
	_                                     CLogin                   = 31
	OnChangeSPWResult                     CLogin                   = 32
	OnCheckSPWExistResult                 CLogin                   = 33
	_                                     CLogin                   = 34
	OnCheckWebLoginEmailID                CLogin                   = 36
	_                                     CLogin                   = 39
	_                                     CLogin                   = 41
	_                                     CLogin                   = 42
	OnChooseGender                        CLogin                   = 43 // Call UI to set gender and second password
	OnGenderSetResult                     CLogin                   = 44 // Saved gender and second password
	_                                     CLogin                   = 45
	_                                     CLogin                   = 46
	_                                     CLogin                   = 47
	OnReceiveHotfix                       CClientSocket            = 49 // Data.wz file bytes
	_                                     CLogin                   = 50
	OpcodeEncryption                      CClientSocket            = 51
	_                                     CLogin                   = 52
	_                                     CLogin                   = 68 // return
	OnInventoryOperation                  CWvsContext              = 91
	OnInventoryGrow                       CWvsContext              = 92
	OnStatChanged                         CWvsContext              = 93
	OnTemporaryStatSet                    CWvsContext              = 94
	OnTemporaryStatReset                  CWvsContext              = 95
	_                                     CWvsContext              = 96
	OnForcedStatSet                       CWvsContext              = 97
	OnForcedStatReset                     CWvsContext              = 98
	OnChangeSkillRecordResult             CWvsContext              = 99
	OnChangeStealMemoryResult             CWvsContext              = 100
	OnUserDamageOnFallingCheck            CWvsContext              = 101
	OnMobDropMesoPickup                   CWvsContext              = 102
	OnBreakTimeFieldEnter                 CWvsContext              = 103
	OnRuneActSuccess                      CWvsContext              = 104
	OnResultStealSkillList                CWvsContext              = 105
	OnSkillUseResult                      CWvsContext              = 106
	OnExclRequest                         CWvsContext              = 107
	_                                     CWvsContext              = 108
	OnGivePopularityResult                CWvsContext              = 109
	_                                     CWvsContext              = 110
	OnMessage                             CWvsContext              = 111
	OnMemoResult                          CWvsContext              = 112
	OnMapTransferResult                   CWvsContext              = 113
	_                                     CWvsContext              = 114
	OnAntiMacroResult                     CWvsContext              = 115
	OnAntiMacroBombResult                 CWvsContext              = 116
	_                                     CWvsContext              = 118
	_                                     CWvsContext              = 119
	_                                     CWvsContext              = 120
	OnClaimResult                         CWvsContext              = 122
	OnSetClaimSvrAvailableTime            CWvsContext              = 123
	OnClaimSvrStatusChanged               CWvsContext              = 124
	_                                     CWvsContext              = 125
	_                                     CWvsContext              = 126
	OnSetTamingMobInfo                    CWvsContext              = 127
	OnQuestClear                          CWvsContext              = 128
	OnEntrustedShopCheckResul             CWvsContext              = 129
	OnSkillLearnItemResult                CWvsContext              = 130
	OnSkillResetItemResult                CWvsContext              = 131
	OnAbilityResetItemResult              CWvsContext              = 132
	OnExpConsumeItemResult                CWvsContext              = 133
	OnExpItemGetResult                    CWvsContext              = 134
	OnCharSlotIncResult                   CWvsContext              = 135
	OnGatherItemResult                    CWvsContext              = 136
	OnSortItemResult                      CWvsContext              = 137
	OnCharacterInfo                       CWvsContext              = 139
	OnPartyResult                         CWvsContext              = 140
	OnPartyMemberCandidateResult          CWvsContext              = 141
	OnUrusPartyMemberCandidateResult      CWvsContext              = 142
	OnPartyCandidateResult                CWvsContext              = 143 // Call CPartyList::OnPacket
	OnPartyCandidateResult2               CWvsContext              = 144 // Call CUIUserList::OnPartyPacket
	OnUrusPartyResult                     CWvsContext              = 145
	OnIntrusionFriendCandidateResult      CWvsContext              = 146
	OnIntrusionLobbyCandidateResult       CWvsContext              = 147
	OnExpedtionResult                     CWvsContext              = 149
	OnFriendResult                        CWvsContext              = 150
	OnGuildRequest                        CWvsContext              = 151
	OnGuildResult                         CWvsContext              = 152
	OnAllianceResult                      CWvsContext              = 153
	OnTownPortal                          CWvsContext              = 154
	OnBroadcastMsg                        CWvsContext              = 155
	OnIncubatorResult                     CWvsContext              = 156
	OnIncubatorHotItemResult              CWvsContext              = 157
	OnMarriageRequest                     CWvsContext              = 158
	OnMarriageResult                      CWvsContext              = 159
	OnWeddingGiftResult                   CWvsContext              = 160
	OnNotifyMarriedPartnerMapTransfer     CWvsContext              = 161
	_                                     CWvsContext              = 162
	OnCashPetFoodResult                   CWvsContext              = 163
	OnCashPetPickUpOnOffResult            CWvsContext              = 164
	OnCashPetSkillSettingResult           CWvsContext              = 165
	OnCashLookChangeResult                CWvsContext              = 166
	OnCashPetDyeingResult                 CWvsContext              = 167
	OnSetWeekEventMessage                 CWvsContext              = 168
	OnSetPotionDiscountRate               CWvsContext              = 169
	OnBridleMobCatchFail                  CWvsContext              = 170
	_                                     CWvsContext              = 171 // CInPacket::Decode1
	OnImitatedNPCData                     CWvsContext              = 173
	OnMonsterBookSetCard                  CWvsContext              = 174
	OnMonsterBookSetCover                 CWvsContext              = 175
	HourChanged                           CWvsContext              = 176
	OnMiniMapOnOff                        CWvsContext              = 177
	OnConsultAuthkeyUpdate                CWvsContext              = 178
	OnClassCompetitionAuthkeyUpdate       CWvsContext              = 179
	OnWebBoardAuthkeyUpdate               CWvsContext              = 180
	OnSessionValue                        CWvsContext              = 181
	OnPartyValue                          CWvsContext              = 182
	OnFieldSetVariable                    CWvsContext              = 183
	OnFieldValue                          CWvsContext              = 184
	OnBonusExpRateChanged                 CWvsContext              = 185
	_                                     CWvsContext              = 186
	OnNotifyLevelUp                       CWvsContext              = 187
	OnNotifyWedding                       CWvsContext              = 188
	OnNotifyJobChange                     CWvsContext              = 189
	OnSetBuyEquipExt                      CWvsContext              = 190 // CInPacket::Decode1
	OnSetPassenserRequest                 CWvsContext              = 191
	OnScriptProgressMessageBySoul         CWvsContext              = 192
	OnScriptProgressMessage               CWvsContext              = 193
	OnScriptProgressItemMessage           CWvsContext              = 194
	OnStaticScreenMessage                 CWvsContext              = 195
	OffStaticScreenMessage                CWvsContext              = 196
	OnWeatherEffectNotice                 CWvsContext              = 197
	OnWeatherEffectNoticeY                CWvsContext              = 198
	_                                     CWvsContext              = 199
	OnPenaltyMessage                      CWvsContext              = 200 // -80% EXP
	_                                     CWvsContext              = 201
	OnProgressMessageFont                 CWvsContext              = 202
	OnDataCRCCheckFailed                  CWvsContext              = 203
	_                                     CWvsContext              = 204
	OnShowSlotMessage                     CWvsContext              = 205
	OnWildHunterInfo                      CWvsContext              = 206
	OnZeroTag                             CWvsContext              = 207
	OnZeroInfo                            CWvsContext              = 208
	OnZeroWP                              CWvsContext              = 209
	OnZeroInfoSubHP                       CWvsContext              = 210
	ClearAnnouncedQuest                   CWvsContext              = 211
	OnResultInstanceTable                 CWvsContext              = 212
	OnCoolTimeSet                         CWvsContext              = 213
	OnItemPotChange                       CWvsContext              = 214
	OnSetItemCoolTime                     CWvsContext              = 215
	OnSetAdDisplayInfo                    CWvsContext              = 216
	OnSetAdDisplayStatus                  CWvsContext              = 217
	OnSetSonOfLinkedSkillResult           CWvsContext              = 218
	_                                     CWvsContext              = 219
	_                                     CWvsContext              = 220
	_                                     CWvsContext              = 221
	_                                     CWvsContext              = 222
	OnSetMapleStyleInfo                   CWvsContext              = 223
	OnSetBuyLimitCount                    CWvsContext              = 224
	OnResetBuyLimitCount                  CWvsContext              = 225
	_                                     CWvsContext              = 226
	_                                     CWvsContext              = 227
	OnUpdateUIEventListInfo               CWvsContext              = 228
	_                                     CWvsContext              = 229
	_                                     CWvsContext              = 230
	CUIFI_OnPacket                        CUIFieldItem             = 231 // CWvsContext::OnPacket
	CUIFII_OnPacket                       CUIFieldItemInventory    = 232 // CWvsContext::OnPacket
	OnResultSetStealSkill                 CWvsContext              = 234
	_                                     CWvsContext              = 235
	OnSlashCommand                        CWvsContext              = 236
	OnStartNavigation                     CWvsContext              = 237
	_                                     CWvsContext              = 238
	OnFunckeySetByScript                  CWvsContext              = 239
	OnCharacterPotentialSet               CWvsContext              = 240
	OnCharacterPotentialReset             CWvsContext              = 241
	OnCharacterHonorExp                   CWvsContext              = 242
	OnReadyForRespawn                     CWvsContext              = 243
	OnReadyForRespawnByPoint              CWvsContext              = 244
	OpenReadyForRespawnUI                 CWvsContext              = 245
	OnCharacterHonorGift                  CWvsContext              = 246
	OnCrossHunterCompleteResult           CWvsContext              = 247
	OnCrossHunterShopResult               CWvsContext              = 248
	_                                     CWvsContext              = 249
	OnSetCashItemNotice                   CWvsContext              = 250
	OnSetSpecialCashItem                  CWvsContext              = 251
	OnShowEventNotice                     CWvsContext              = 252
	OnBoardGameResult                     CWvsContext              = 253
	OnValuePackResult                     CWvsContext              = 255
	OnNaviFlyingResult                    CWvsContext              = 256
	OnMapleStyleResult                    CWvsContext              = 257
	OnCheckWeddingExResult                CWvsContext              = 258
	OnBingoResult                         CWvsContext              = 259
	OnBingoCassandraResult                CWvsContext              = 260
	OnUpdateVIPGrade                      CWvsContext              = 261
	OnMesoRangerResult                    CWvsContext              = 262
	OnSetMaplePoint                       CWvsContext              = 263
	OnAdditionalCashInfo                  CWvsContext              = 264 // CInPacket::DecodeBuffer(8)
	OnSetMiracleTimeInfo                  CWvsContext              = 265
	OnHyperSkillResetResult               CWvsContext              = 266
	OnGetServerTime                       CWvsContext              = 267
	OnGetCharacterPosition                CWvsContext              = 268
	OnSetFixDamage                        CWvsContext              = 270
	OnSetFixDamage2                       CWvsContext              = 271
	OnReturnEffectConfirm                 CWvsContext              = 272
	OnReturnEffectModified                CWvsContext              = 273
	OnWhiteAddtionalCubeResult            CWvsContext              = 274
	OnBlackCubeResult                     CWvsContext              = 275
	OnMemorialCubeResult                  CWvsContext              = 276
	OnMemorialCubeModified                CWvsContext              = 277
	OnBlackRebirthResult                  CWvsContext              = 278
	OnBlackRebirthScroll                  CWvsContext              = 279
	OnRebirthScrollWindow                 CWvsContext              = 280
	OnDressUpInfoModified                 CWvsContext              = 281
	_                                     CWvsContext              = 282
	OnResetOnStateForOnOffSkill           CWvsContext              = 283
	OnSetOffStateForOnOffSkill            CWvsContext              = 284
	OnIssueReloginCookie                  CWvsContext              = 285
	OnAvatarPackTest                      CWvsContext              = 286
	OnEvolvingResult                      CWvsContext              = 287
	OnActionBarResult                     CWvsContext              = 288
	CUIGCR_OnPacket                       CUIGuildContentRank      = 289 // CWvsContext::OnPacket
	OnGuildSearchResult                   CWvsContext              = 290
	CUIBFC_OnPacket                       CUIButterFlyCustomize    = 291 // CWvsContext::OnPacket
	OnHalloweenCandyRankingResult         CWvsContext              = 292
	OnGetRewardResult                     CWvsContext              = 293
	OnMentoring                           CWvsContext              = 294
	OnGetLotteryResult                    CWvsContext              = 295
	OnCheckProcessResult                  CWvsContext              = 296
	OnCompleteNpcSpeechSuccess            CWvsContext              = 297
	OnCompleteSpecialCheckSuccess         CWvsContext              = 298
	OnSetAccountInfo                      CWvsContext              = 299
	OnSetGachaponFeverTimeInfo            CWvsContext              = 300
	OnAvatarMegaphoneRes                  CWvsContext              = 301
	OnSetAvatarMegaphone                  CWvsContext              = 302
	OnClearAvatarMegaphone                CWvsContext              = 303
	OnRequestEventList                    CWvsContext              = 304
	_                                     CWvsContext              = 305
	OnLikePoint                           CWvsContext              = 306
	OnSignErrorAck                        CWvsContext              = 307
	OnAskAfterErrorAck                    CWvsContext              = 308
	OnEventNameTag                        CWvsContext              = 309
	OnAcquireEventNameTag                 CWvsContext              = 310
	OnJobFreeChangeResult                 CWvsContext              = 311
	OnEventLotteryOpen                    CWvsContext              = 312
	OnEventLotteryResult                  CWvsContext              = 313
	OnInvasionSupportStateChange          CInvasionSupportMan      = 314 // CWvsContext::OnPacket
	OnInvasionSupportAttackResult         CInvasionSupportMan      = 315 // CWvsContext::OnPacket
	OnBossKillResult                      CInvasionSupportMan      = 316 // CWvsContext::OnPacket
	OnInvasionSupportSettingResult        CInvasionSupportMan      = 317 // CWvsContext::OnPacket
	OnInvasionElapsedTime                 CInvasionSupportMan      = 318 // CWvsContext::OnPacket
	OnInvasionSystemMsg                   CInvasionSupportMan      = 319 // CWvsContext::OnPacket
	_                                     CWvsContext              = 322
	OnScreenMsg                           CWvsContext              = 323
	OnLimitGoodsNoticeResult              CWvsContext              = 324
	OnUniverseBossPossible                CWvsContext              = 327
	OnUniverseBossImpossible              CWvsContext              = 328
	OnCashShopPreviewInfo                 CWvsContext              = 329
	OnChangeSoulCollectionResult          CWvsContext              = 330
	OnSelectSoulCollectionResult          CWvsContext              = 331
	OnMasterPieceReward                   CWvsContext              = 332
	OnPendantSlotIncResult                CWvsContext              = 333
	OnBossArenaMatchSuccess               CWvsContext              = 334
	OnBossArenaMatchFail                  CWvsContext              = 335
	OnBossArenaMatchRequestDone           CWvsContext              = 336
	OnUserSoulMatching                    CWvsContext              = 337
	OnCatapultUpgradeSkill                CWvsContext              = 338
	OnCatapultResetSkill                  CWvsContext              = 339
	OnPartyQuestRankingResult             CWvsContext              = 340
	OnSetCoordinationContestInfo          CWvsContext              = 341
	OnWorldTransferResult                 CWvsContext              = 342
	OnTrunkSlotIncResult                  CWvsContext              = 343
	OnEliteMobWMI                         CWvsContext              = 344
	OnRandomPortalNotice                  CWvsContext              = 345
	OnNotifyWorldTransferHelper           CWvsContext              = 346
	_                                     CWvsContext              = 347
	CUIEE_OnPacket                        CUIEquipmentEnchant      = 348 // CWvsContext::OnPacket
	OnTopTowerRankResult                  CWvsContext              = 349
	OnFriendTowerRankResult               CWvsContext              = 350
	OnTowerResultUIOpen                   CWvsContext              = 351
	_                                     CWvsContext              = 352
	_                                     CWvsContext              = 353
	_                                     CWvsContext              = 354
	_                                     CWvsContext              = 355
	CKoreanJumpingGame                    CWvsContext              = 356
	OnCreateSwingGame                     CWvsContext              = 357
	OnUpdateMapleTVShowTime               CWvsContext              = 358
	OnReturnToTitle                       CWvsContext              = 359
	OnReturnToCharacterSelect             CWvsContext              = 360
	OnFlameWizardFlameWalkEffect          CWvsContext              = 361
	_                                     CWvsContext              = 362
	OnSummonedAvatarSync                  CWvsContext              = 363
	OnMixLense                            CWvsContext              = 510
	OnQuickPass                           CWvsContext              = 515 // CInPacket::Decode4
	OnUseMakeUpCoupon                     CWvsContext              = 516
	OnChatEmoticon                        CWvsContext              = 518
	OnBlizzardTempest                     CWvsContext              = 522
	HyperPreset                           CWvsContext              = 545
	OnMacroSysDataInit                    CWvsContext              = 552
	OnSetField                            CStage                   = 553
	OnSetFarmField                        CStage                   = 555
	OnSetAuctionField                     CStage                   = 556
	OnSetCashShop                         CStage                   = 557
	OnTransferFieldReqIgnored             CField                   = 558
	OnTransferChannelReqIgnored           CField                   = 559
	OnTransferPvpReqIgnored               CField                   = 560
	OnFieldSpecificData                   CField                   = 561
	OnGroupMessage                        CField                   = 562
	OnItemGroupMessage                    CField                   = 563
	OnFieldUniverseMessage                CField                   = 564
	OnWhisper                             CField                   = 565
	OnSummonItemInavailable               CField                   = 566
	OnFieldEffect                         CField                   = 567
	OnBlowWeather                         CField                   = 568
	OnPlayJukeBox                         CField                   = 569
	OnAdminResult                         CField                   = 570
	OnQuiz                                CField                   = 571
	OnDesc                                CField                   = 572
	OnClock                               CField                   = 573
	OnContiMove                           CField                   = 574
	OnContiState                          CField                   = 575
	OnSetQuestClear                       CField                   = 578
	OnSetQuestTime                        CField                   = 579
	OnSetObjectState                      CField                   = 580
	OnDestroyClock                        CField                   = 581
	OnStalkResult                         CField                   = 582
	MassacreIncGauge                      CField                   = 583
	MassacreResult                        CField                   = 585
	CQKMM_OnInit                          CQuickslotKeyMappedMan   = 588 // CField::OnPacket
	OnFootHoldMove                        CField                   = 589
	OnCorrectFootHoldMove                 CField                   = 590
	DynamicObjMove                        CField                   = 591
	DynamicObjVisible                     CField                   = 592
	DynamicFootholdSync                   CField                   = 593
	FieldKillCount                        CField                   = 594
	OnSmartMobNotice                      CField                   = 596
	OnChangePhase                         CField                   = 597
	OnChangeMobZone                       CField                   = 598
	OnPvPMigrateInfoResult                CField                   = 600
	OnCurNodeEventEnd                     CInGameDirectionNodeInfo = 601 // CField::OnPacket
	OnCreateForceAtom                     CField                   = 602
	OnSpawnBullet                         CField                   = 603
	OnRemoveForceAtom                     CField                   = 604
	OnForceAtomAttack                     CField                   = 605
	OnSetAchieveRate                      CField                   = 606
	OnSetQuickMoveInfo                    CField                   = 607
	OnCreateObtacle                       CField                   = 608
	OnCreateObtacle2                      CField                   = 609 // Not sure
	OnClearObtacle                        CField                   = 610
	_                                     CField                   = 611
	OnB2FootHoldCreate                    CField                   = 612
	_                                     CField                   = 613
	_                                     CField                   = 614
	_                                     CField                   = 615
	OnDebuffObjON                         CField                   = 616
	OnCreateFallingCatcher                CField                   = 617
	OnChaseEffectSet                      CField                   = 618
	OnMesoExchangeResult                  CWvsApp                  = 619 // CField::OnPacket
	OnSetMirrorDungeonInfo                CField                   = 620
	OnSetIntrusion                        CField                   = 621
	OnCannotDrop                          CField                   = 622
	OnFootHoldOnOff                       CField                   = 623
	OnLadderRopeOnOff                     CField                   = 624
	OnMomentAreaOnOff                     CField                   = 625
	OnMomentAreaOnOffAll                  CField                   = 626
	OnChatLetClientConnect                CField                   = 627
	CUICC_OnPacket                        CUICoordinationContest   = 628 // CField::OnPacket
	OnEliteState                          CField                   = 629
	OnPlaySound                           CField                   = 630
	OnStackEventGauge                     CField                   = 631
	OnSetUnionField                       CField                   = 632
	_                                     CField                   = 633
	OnSpecialeEffect                      CField                   = 634 // Not sure
	OnSpecialSound                        CField                   = 635 // Not sure
	_                                     CField                   = 636
	OnStardustUI                          CField                   = 638
	OnGainCharacterExp                    CField                   = 639
	_                                     CField                   = 640
	_                                     CField                   = 641
	OnZodiacInfo                          CField                   = 642 // Not sure
	OnPublicShareState                    CField                   = 643
	OnFunctionTempBlock                   CField                   = 644
	CUISB_OnPacket                        CUIStatusBar             = 645 // CField::OnPacket
	OnFieldSkillDelay                     FieldDelaySkill          = 646 // CField::OnPacket
	OnFieldSkill                          CField                   = 647
	OnFieldSkillRemove                    CField                   = 648
	_                                     CField                   = 649
	OnWeatherPacket_Add                   CField                   = 650
	OnWeatherPacket_Remove                CField                   = 651
	OnWeatherPacket_Msg                   CField                   = 652
	OnAddWreckage                         CField                   = 653
	OnDelWreckage                         CField                   = 654
	OnCreateMirrorImage                   CField                   = 655
	OnFuntionFootholdMan                  CField                   = 656
	OnSpecialChair                        CField                   = 657
	OnInviteChair                         CField                   = 658
	OnLucid                               CField                   = 660 // BOSS not sure
	OnActivePotionCD                      CField                   = 662
	_                                     CField                   = 666
	OnSpecialMapEffect                    CField                   = 667
	OnGiantMonsterGloomDiedImage          CField                   = 668 // BOSS
	_                                     CField                   = 670
	_                                     CField                   = 671
	_                                     CField                   = 672
	OnUpdateGuildScore                    CField                   = 673
	OnRankCreate                          CField                   = 1526
	SetUserName                           CFieldRankSystem         = 1527 // CField::OnPacket
	NotifyData                            CFieldRankSystem         = 1528 // CField::OnPacket
	OnFieldFadeObjectInfo                 CField                   = 1568
	OnRuneStoneClearAndAllRegister        CRuneStoneMgrForClient   = 1569 // CField::OnPacket
	OnRuneStoneDisappear                  CRuneStoneMgrForClient   = 1570 // CField::OnPacket
	OnCheckSPWOnCreateNewCharacterResult  CLogin                   = 2215
	OnSetSPWResult                        CLogin                   = 2216
)
